version: "3.9"

services:
  udc-server:
    build: .
    container_name: udc_asset_tagging
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - DB_PATH=tags.db
      - DATA_DIR=./data
      - SERVER_PORT=8080
    volumes:
      - ./data:/app/data
      - ./tags.db:/app/tags.db
